const blogData = [
    {
      id: 1,
      title: "The Future of AI: What's Next?",
      description: "Discover the latest advancements in artificial intelligence.",
      category: "AI",
      date: "2025-03-05",
      author: "John Doe",
      readingTime: 5,
      tags: ["AI", "Machine Learning", "Future Tech"],
      image: "/images/ai-future.jpg",
      views: 2000,
      engagement: 150,
    },
    {
      id: 2,
      title: "Cloud Computing Trends in 2025",
      description: "Explore the top trends shaping cloud computing.",
      category: "Cloud Computing",
      date: "2025-03-02",
      author: "Alice Smith",
      readingTime: 4,
      tags: ["Cloud", "DevOps", "Innovation"],
      image: "/images/cloud-trends.jpg",
      views: 3500,
      engagement: 250,
    },
    {
      id: 3,
      title: "Cybersecurity Best Practices for 2025",
      description: "Stay protected with these expert cybersecurity tips.",
      category: "Cybersecurity",
      date: "2025-03-01",
      author: "Michael Lee",
      readingTime: 6,
      tags: ["Cybersecurity", "Hacking", "Privacy"],
      image: "/images/cybersecurity.jpg",
      views: 2800,
      engagement: 200,
    },
    {
      id: 4,
      title: "Mastering Mobile App Development",
      description: "Learn the essentials of building high-performance mobile apps.",
      category: "Mobile App",
      date: "2025-03-06",
      author: "Emma Johnson",
      readingTime: 7,
      tags: ["Mobile App", "Android", "iOS"],
      image: "/images/mobile-app.jpg",
      views: 2200,
      engagement: 180,
    },
    {
      id: 5,
      title: "The Rise of Modern Web Development",
      description: "A look at the latest tools and technologies shaping web development.",
      category: "Web Development",
      date: "2025-03-04",
      author: "David Brown",
      readingTime: 6,
      tags: ["Web Development", "Frontend", "Backend"],
      image: "/images/web-development.jpg",
      views: 3000,
      engagement: 210,
    },
    {
      id: 6,
      title: "Sketching Techniques for Beginners",
      description: "A guide to improve your sketching skills with simple techniques.",
      category: "Sketching & Art",
      date: "2025-03-03",
      author: "Sophia Adams",
      readingTime: 5,
      tags: ["Sketching", "Art", "Drawing"],
      image: "/images/sketching.jpg",
      views: 1700,
      engagement: 140,
    },
    {
      id: 7,
      title: "The Benefits of Organic Products",
      description: "Why switching to organic products is better for health and the environment.",
      category: "Organic Products",
      date: "2025-03-07",
      author: "James Wilson",
      readingTime: 4,
      tags: ["Organic", "Health", "Sustainability"],
      image: "/images/organic-products.jpg",
      views: 2600,
      engagement: 190,
    },
    {
      id: 8,
      title: "Digital Marketing Strategies for 2025",
      description: "Top strategies to boost your online presence and grow your business.",
      category: "Digital Marketing",
      date: "2025-03-06",
      author: "Olivia Martinez",
      readingTime: 6,
      tags: ["Digital Marketing", "SEO", "Social Media"],
      image: "/images/digital-marketing.jpg",
      views: 3400,
      engagement: 230,
    },
    {
      id: 9,
      title: "Photography & Videography Tips",
      description: "Enhance your photography and videography skills with expert advice.",
      category: "Photography & Videography",
      date: "2025-03-05",
      author: "Ethan White",
      readingTime: 5,
      tags: ["Photography", "Videography", "Editing"],
      image: "/images/photography.jpg",
      views: 2800,
      engagement: 220,
    },
  ];
  

  export default blogData;